[build]
target-dir = "build-cache"

[target.x86_64-unknown-linux-gnu]
linker = "x86_64-unknown-linux-gnu-gcc"
# You might also need to specify AR and CC explicitly, though Cargo often infers CC from the linker.
# cc = "x86_64-unknown-linux-gnu-gcc"
# ar = "x86_64-unknown-linux-gnu-ar"

[dependencies.openssl-sys]
version = "0.9.109" # Use your actual version
features = ["vendored"]
